app/config/routes.rb
# frozen_string_literal: true

# A constraint to allow certain routes to authenticated monkeys only
admin_constraint = lambda do |request|
  request.env['warden'].authenticated?(:admin_user) || Rails.env.development?
end

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  constraints admin_constraint do
    mount GoodJob::Engine => '/jobs'
  end

  devise_for :users

  # Reveal health status on /up that returns 200 if the app boots with no exceptions,
  # otherwise 500. Can be used by load balancers and uptime monitors to verify
  # that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # scope module: 'api' do
  #   namespace :v1 do
  #   end
  # end

  resources :profiles, only: %i[index show edit update] do
    resources :chats, only: :create
  end
  resources :chats, except: :create do
    resources :messages, only: [:index, :create]
  end

  # Render dynamic PWA files from app/views/pwa/*
  # (Manifest linked from application.html.erb)
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker

  # get '/:locale' => 'home#index', as: 'root_i18n'

  # Defines the root path route ("/")
  root 'home#index'
end

app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full" data-theme="lukin" lang="<%= I18n.locale %>">
  <head>
    <title><%= content_for(:title) || "U Lukin ?" %></title>
    <meta name="viewport"
          content="width=device-width, initial-scale=1, user-scalable=no, viewport-fit=cover">
    <%# Disable turbo prefetching for now, to reduce the number of events sent to PH %>
    <meta name="turbo-prefetch" content="true">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <%= favicon_link_tag '/favicon.ico' %>

    <%= vite_client_tag %>
    <%= vite_javascript_tag 'application' %>
    <%= vite_stylesheet_tag 'application.tailwind.css' %>
  </head>

  <body class="min-h-screen-safe h-auto flex flex-col bg-slate-900 mt-safe">

    <main class="w-full lukin flex flex-col self-center">
      <%= yield %>
    </main>
</html>