app/config/routes.rb
# frozen_string_literal: true

# A constraint to allow certain routes to authenticated monkeys only
admin_constraint = lambda do |request|
  request.env['warden'].authenticated?(:admin_user) || Rails.env.development?
end

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  constraints admin_constraint do
    mount GoodJob::Engine => '/jobs'
  end

  devise_for :users

  # Reveal health status on /up that returns 200 if the app boots with no exceptions,
  # otherwise 500. Can be used by load balancers and uptime monitors to verify
  # that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # scope module: 'api' do
  #   namespace :v1 do
  #   end
  # end

  resources :profiles, only: %i[index show edit update] do
    resources :chats, only: :create
  end
  resources :chats, except: :create do
    resources :messages, only: [:index, :create]
  end

  # Render dynamic PWA files from app/views/pwa/*
  # (Manifest linked from application.html.erb)
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker

  # get '/:locale' => 'home#index', as: 'root_i18n'

  # Defines the root path route ("/")
  root 'home#index'
end

app/app/models/profile.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: profiles
#
#  id           :uuid             not null, primary key
#  age          :integer
#  body         :integer          default("unknown"), not null
#  data         :jsonb            not null
#  gender       :integer          default("unknown"), not null
#  height       :integer
#  location     :geography        point, 4326
#  position     :integer          default("unknown"), not null
#  relationship :integer          default("unknown"), not null
#  weight       :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :uuid             not null
#
# Indexes
#
#  index_profiles_on_location            (location) USING gist
#  index_profiles_on_updated_at_and_age  (updated_at,age)
#  index_profiles_on_user_id             (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Profile < ApplicationRecord
  ACTIVE = 30.minutes
  CONNECTED = 3.days

  belongs_to :user, optional: false
  has_many :chat_links
  has_many :chats, through: :chat_links

  has_one_attached :picture do |pic|
    pic.variant :thumbnail, resize_to_fill: [500, 500]
  end

  jsonb_accessor :data,
    title: [:string, default: ''],
    bio: [:string, default: ''],
    hide_distance: [:boolean, default: false],
    hide_age: [:boolean, default: false],
    hide_height: [:boolean, default: false],
    hide_weight: [:boolean, default: false]

  enum :position, {
      unknown: 0, soft: 1, top: 2, versatile_top: 3, versatile: 4,
      versatile_bottom: 5, bottom: 6,
    }, prefix: true
  enum :body, {
      unknown: 0, thin: 1, average: 2, toned: 3, muscular: 5, large: 6
    }, prefix: true
  enum :gender, {
      unknown: 0, other: 1, cis: 2, queer: 3, trans: 4, non_binary: 5, fluid: 6, nope: 7
    }, prefix: true
  enum :relationship, {
      unknown: 0, single: 1, couple: 2, free_couple: 3, married: 4, poly: 5
    }, prefix: true

  scope :with_distance, lambda { |point|
    select('*', arel_table[:location].st_distance(Arel.spatial(point)).as('distance'))
  }
  scope :by_distance, ->(point) { with_distance(point).order(distance: :asc) }
  scope :connected, -> { where('updated_at > ?', CONNECTED.ago ) }

  validates :age, numericality: { greater_than_or_equal_to: 18 }
  validates :height, numericality: { in: (50..260) }
  validates :weight, numericality: { in: (10..500) }

  validates :picture, blob: {
      content_type: ["image/png", "image/jpg", "image/jpeg", "image/webp"],
      size_range: 1..(8.megabytes)
    }

  def self.location_factory
    # Longitude, Latitude
    @location_factory ||= RGeo::Geographic.spherical_factory(srid: 4326)
  end

  # We assume the user is online/active if they updated their profile/location recently
  def active?
    updated_at > ACTIVE.ago
  end

  def hide_nothing!
    update(
      hide_age: false,
      hide_position: false,
      hide_height: false,
      hide_weight: false,
      hide_body: false
    )
  end
end

app/app/controllers/profiles_controller.rb
# frozen_string_literal: true

class ProfilesController < ApplicationController
  before_action :load_profiles, only: :index
  before_action :load_profile, only: :show

  def index
  end

  def show
  end

  def edit
    @profile = current_profile
  end

  def update
    @profile = current_profile

    if @profile.update(profile_params)
      redirect_to profile_path(current_profile), notice: "Profile updated"
    else
      render :edit, status: :unprocessable_content
    end
  end

  private

  def profile_params
    params.require(:profile).permit(
      :title, :bio, :age, :weight, :height,
      :body, :position, :gender, :relationship
    )
  end

  def load_profile
    @profile = Profile
      .with_distance(current_location)
      .find(params[:id])
    @distance = @profile.distance if @profile.respond_to?(:distance)
  end

  def load_profiles
    @profiles = Profile
      .by_distance(current_location)
      .connected
      .limit(40)
  end
end

app/app/helpers/profile_helper.rb
# frozen_string_literal: true

module ProfileHelper
  def format_distance(distance)
    return if distance.blank?

    if distance < 1000
      meters = distance.round(-2)
      "~#{ meters } m"
    else
      km = (distance / 1000.0)
      if km > 10
        km = km.round
      else
        km = km.round(1)
      end
      "#{km} km"
    end
  end

  def format_attr_height(value)
    "#{value / 100.0} m"
  end

  def format_attr_weight(value)
    "#{value} kg"
  end

  def format_attr_position(value)
    Profile.human_enum_name(:position, value)
  end

  def format_attr_body(value)
    Profile.human_enum_name(:body, value)
  end

  def format_attr_gender(value)
    Profile.human_enum_name(:gender, value)
  end

  def format_attr_relationship(value)
    Profile.human_enum_name(:relationship, value)
  end
end

app/app/views/profiles/_grid.html.erb
<!-- Profiles Grid -->
<% if profiles.any? %>
  <div class="grid grid-cols-3 lg:grid-cols-6 gap-[2px]">
    <% profiles.each do |profile| %>
      <a href="<%= profile_path(profile) %>"
        class="relative profile-card bg-neutral overflow-hidden transition-all
               duration-300 hover:scale-[1.02]">

        <!-- Profile Image Placeholder -->
        <div class="">
          <% if profile.picture.attached? %>
            <div class="aspect-square bg-gradient-to-br from-secondary/20
                        to-primary/20 flex items-center justify-center">
              <%= image_tag(
                profile.picture.variant(:thumbnail),
                class: "object-cover aspect-square",
                loading: 'lazy'
              ) %>
            </div>

          <% else %>
            <div class="aspect-square bg-gradient-to-br from-secondary/20
                        to-primary/20 flex items-center justify-center">
              <%= lucide_icon('user', class: 'w-8 h-8 text-secondary') %>
            </div>
          <% end %>
        </div>

        <!-- Profile Title & Presence -->
        <div class="absolute bottom-0 w-full">
          <div class="flex items-center justify-left gap-1 py-1 px-2 bg-base-100/60">
            <% if profile.active? %>
              <div class="w-2 h-2 rounded-full bg-primary border-gray-500"></div>
            <% end %>
            <h3 class="text-sm truncate tracking-wide">
              <%= profile.title.presence %>
            </h3>
          </div>
        </div>
      </a>
    <% end %>
  </div>
<% else %>
  <div class="text-center py-12">
    <div class="mx-auto w-16 h-16 rounded-full bg-neutral flex items-center justify-center mb-4">
      <%= lucide_icon('users', class: 'w-8 h-8 text-neutral-content') %>
    </div>
    <h3 class="text-lg font-medium text-neutral-content">No profiles found</h3>
    <p class="mt-1 text-sm text-neutral-content">Try adjusting your filters or check back later</p>
  </div>
<% end %>

app/app/views/profiles/_index_footer.html.erb
<!-- Footer navigation links would go here -->
<div class="h-full w-full flex justify-around items-center">
  <a href="<%= profiles_path %>" class="grow btn btn-ghost rounded-none">
    <%= lucide_icon :users, class: 'w-5 h-5' %>
  </a>
  <a href="<%= profiles_path %>" class="grow btn btn-ghost rounded-none">
    <%= lucide_icon 'message-square', class: 'w-5 h-5' %>
  </a>
</div>

app/app/views/profiles/_index_header.html.erb
<!-- Header -->
<div class="flex items-center justify-between h-12">
  <div class="flex items-center">
    <a class="text-xl font-bold" href="<%= edit_profile_path('me')  %>">
      <div class="w-8 h-8 ring-1 rounded-full overflow-hidden flex items-center justify-center">
        <% if current_profile.picture.attached? %>
          <%= image_tag current_profile.picture.variant(:thumbnail), class: "w-full h-full object-cover" %>
        <% else %>
          <%= lucide_icon('user', class: 'w-8 h-8 text-gray-500') %>
        <% end %>
      </div>
    </a>
    <h1 class="ml-3 text-xl font-bold">U Lukin ?</h1>
  </div>
  <div class="flex items-center space-x-4">
    <!-- Add filter/sort icons here if needed -->
    <%= lucide_icon('filter', class: 'w-5 h-5') %>
  </div>
</div>

app/app/views/profiles/edit.html.erb
<div class="bg-base-100 text-white min-h-screen-safe w-screen flex flex-col">
  <!-- Header -->
  <div class="sticky top-0 z-10 bg-base-100/90 backdrop-blur-sm border-b border-neutral">
    <div class="flex items-center justify-between px-4 py-3">
      <a href="<%= profile_path(@profile) %>"
         class="btn btn-circle bg-base-100/85 hover:bg-base-100 border-0">
        <%= lucide_icon('arrow-left', class: 'w-6 h-6') %>
      </a>

      <h1 class="text-xl font-accent">Edit Profile</h1>

      <div class="w-6"></div> <!-- Spacer for symmetry -->
    </div>
  </div>

  <!-- Main content -->
  <div class="flex-grow overflow-y-auto">
    <%= simple_form_for @profile do |f| %>
      <!-- Profile Picture Section -->
      <div class="bg-base-200 border-b pb-4 border-neutral">
        <div class="flex flex-col items-center gap-4">
          <% if @profile.picture.attached? %>
            <%= image_tag @profile.picture, class: "w-full object-cover aspect-square" %>
          <% else %>
            <div class="flex items-center justify-center w-full aspect-square
                        bg-gradient-to-br from-secondary/20 to-primary/20 ">
              <%= lucide_icon('user', class: 'w-40 h-40 text-gray-400') %>
            </div>
          <% end %>

          <div class="w-full px-4">
            <%= f.file_field(
              :picture,
              class: "file-input file-input-bordered w-full",
              accept: 'image/webp, image/jpeg, image/png'
            ) %>
          </div>
        </div>
      </div>

      <!-- Basic Info Section -->
      <div class="bg-base-200 rounded-xl p-4">
        <h2 class="text-lg mb-3">
          Your profile
        </h2>

        <div class="space-y-4">
          <!-- Title -->
          <a id="here"></a>
          <%= f.input(
            :title,
            wrapper: :icon_input,
            label: false,
            lucide_icon: 'user',
            placeholder: 'Profile title',
            lucide_icon_class: 'text-gray-500',
            label_html: {class: 'font-accent'},
          ) %>


          <!-- Bio -->
          <div>
            <label class="form-control">
              <!-- <div class="label">
                   </div> -->
              <%= f.input_field(
                :bio, as: :text,
                class: "textarea textarea-bordered h-32",
                placeholder: "Your bio"
              ) %>
              <!-- <div class="label">
                   <span class="label-text-alt">Your bio</span>
                   <span class="label-text-alt">Alt label</span>
                   </div> -->
            </label>
          </div>
        </div>

        <div class="space-y-4 mt-8">
          <!-- Age -->
          <div class="flex items-center gap-4">
            <%= f.input(
              :age,
              type: :number,
              wrapper: :icon_input,
              wrapper_html: {class: 'grow'},
              label: false,
              placeholder: 'Age',
              lucide_icon: 'baby',
              lucide_icon_class: 'text-gray-500',
              input_html: {min: 18},
              label_html: {class: 'font-accent'},
            ) %>

            <div class="h-full flex flex-col items-center justify-end gap-1 shrink">
              <%= f.label :hide_age, "Hide", class: "label-text font-accent" %>
              <%= f.check_box :hide_age, class: "toggle toggle-error" %>
            </div>
          </div>

          <!-- Height -->
          <div class="flex items-center gap-4">
            <%= f.input(
              :height,
              type: :number, label: false, placeholder: 'Height', unit: 'cm',
              wrapper: :icon_input,
              wrapper_html: {class: 'grow'},
              lucide_icon: 'ruler',
              lucide_icon_class: 'text-gray-500',
              input_html: {min: 50, max: 260},
              label_html: {class: 'font-accent'},
            ) %>

            <div class="h-full flex flex-col items-center justify-end gap-1 shrink">
              <%= f.label :hide_height, "Hide", class: "label-text font-accent" %>
              <%= f.check_box :hide_height, class: "toggle toggle-error" %>
            </div>
          </div>

          <!-- Height -->
          <div class="flex items-center gap-4">
            <%= f.input(
              :weight,
              type: :number, label: false, placeholder: 'Weight', unit: 'kg',
              wrapper: :icon_input,
              wrapper_html: {class: 'grow'},
              lucide_icon: 'weight',
              lucide_icon_class: 'text-gray-500',
              input_html: {min: 50, max: 260},
              label_html: {class: 'font-accent'},
            ) %>

            <div class="h-full flex flex-col items-center justify-end gap-1 shrink">
              <%= f.label :hide_height, "Hide", class: "label-text font-accent" %>
              <%= f.check_box :hide_height, class: "toggle toggle-error" %>
            </div>
          </div>
        </div>

        <div class="space-y-4 mt-8">
          <!-- Selectable/Enum attributes (body, position, gender) -->
          <% select_attrs = {
            body: 'person-standing',
            position: 'arrow-up-down',
            gender: 'transgender',
            relationship: 'gem',
          } %>

          <% select_attrs.each do |attribute, icon| %>
            <div class="flex items-center gap-4">
              <div class="ml-3 text-gray-500">
                <%= lucide_icon icon %>
              </div>

              <label class="form-control w-full">
                <%= f.select(
                  attribute,
                  enum_for_select(f.object, attribute),
                  {}, {class: 'select select-bordered'}
                ) %>
              </label>
            </div>
          <% end %>

      <!-- Save Button -->
      <div class="sticky bottom-0 bg-base-100 pt-4 pb-6">
        <%= f.submit "Save Changes", class: "btn btn-primary w-full" %>
      </div>
    <% end %>
  </div>
</div>

app/app/views/profiles/index.html.erb
<div class="bg-base-100 text-white flex flex-col h-screen-safe">
  <!-- Header -->

  <div class="sticky top-0 z-10
              bg-base-100/90 backdrop-blur-sm border-b border-neutral">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <%= render partial: 'index_header' %>
    </div>
  </div>

  <section class="grow overflow-y-auto
                  max-w-5xl mx-auto">
    <!-- Main content area that scrolls -->
    <%= render partial: 'grid', locals: { profiles: @profiles } %>
  </section>

  <!-- Footer -->
  <nav class="grow-0 shrink-0 w-full bg-neutral">
    <%= render partial: 'index_footer' %>
  </nav>
</div>

app/app/views/profiles/show.html.erb
<div class="bg-base-100 text-white min-h-screen-safe w-screen flex flex-col mb-4">
  <!-- Full screen carousel with basic infocs -->
  <div class="relative h-screen-safe w-screen flex flex-col">
    <!-- Profile picture -->
    <% if @profile.picture.attached? %>
      <%= image_tag @profile.picture, class: 'w-full h-full object-cover grow' %>
    <% else %>
      <div class="grow bg-gradient-to-br from-secondary/20
                  to-primary/20 flex items-center justify-center">
        <%= lucide_icon('user', class: 'w-8 h-8 text-secondary') %>
      </div>
    <% end %>

    <!-- Profile title, age & distance, CTA -->
    <div class="grow-0 w-full flex flex-col bg-base-100/50 px-4 pt-6 pb-2">
      <div class="flex items-top justify-between">
        <h1 class="text-2xl font-bold text-white">
          <span><%= @profile.title.presence %></span>
          <span class="ml-2 text-slate-300 font-sm"><%= @profile.age %></span>
        </h1>

        <div class="text-neutral-content">
          <% unless @profile.hide_distance? %>
            <%= format_distance(@distance) %>
          <% end %>
        </div>
      </div>

      <!-- Online or not -->
      <div>
        <% if @profile.active? %>
          <span class="text-success"> Online now </span>
        <% else %>
          <span class="text-neutral-content">
            Online <%= time_ago_in_words @profile.updated_at %> ago
          </span>
        <% end %>
      </div>

      <!-- Chat CTA -->
      <div class="mt-6 w-full flex items-center gap-2">
        <% if @profile == current_profile %>
          <a href="<%= edit_profile_path(current_profile) %>"
            class="btn btn-block">
            Edit your profile
          </a>
        <% else %>
        <a href="<%= profile_chats_path(@profile) %>"
          data-turbo-method="post"
          class="grow text-slate-300 rounded-full p-3 px-4 bg-gray-800
                 text-neutral-content truncate">
          Say something nice...
        </a>
        <a href="#" class="text-slate-300 rounded-full p-2 bg-gray-800">
          <%= lucide_icon :flame, class: 'w-9 h-9'  %>
        </a>
        <a href="<%= profile_chats_path(@profile) %>"
          data-turbo-method="post"
          class="text-slate-300 rounded-full p-2 bg-slate-800">
          <%= lucide_icon 'message-circle', class: 'w-9 h-9'  %>
        </a>
        <% end %>
      </div>
    </div>

    <!-- Top navigation bar with buttons -->
    <div class="absolute top-4 left-0 right-0 px-4 flex justify-between items-center">
      <a href="<%= profiles_path %>"
        class="btn btn-circle bg-base-100/85 hover:bg-base-100 border-0">
        <%= lucide_icon('arrow-left', class: 'w-6 h-6') %>
      </a>

      <div class="flex gap-2">
        <button class="btn btn-circle bg-base-100/85 hover:bg-base-100 border-0">
          <%= lucide_icon('star', class: 'w-6 h-6') %>
        </button>
        <button class="btn btn-circle bg-base-100/85 hover:bg-base-100 border-0">
          <%= lucide_icon('more-horizontal', class: 'w-6 h-6') %>
        </button>
      </div>
    </div>
  </div>

  <!-- Profile section -->
  <div class="px-4 py-6">
    <div class="text-neutral-content flex flex-wrap">
      <%= @profile.bio %>
    </div>
  </div>

  <!-- Attributes section -->
  <div class="text-gray-200">
    <table class="table table-sm md:table-md>
      <thead></thead>
      <tbody>
        <% %i[weight height].each do |name| %>
          <% if @profile.send(name).present? && !@profile.send("hide_#{name}") %>
            <tr class="text-lg">
              <td class="font-accent font-light">
                <%= Profile.human_attribute_name(name) %>
              </td>
              <td>
                <%= send "format_attr_#{name}", @profile.send(name) %>
              </td>
            </tr>
          <% end %>
        <% end %>

        <% %i[position body gender relationship].each do |name| %>
          <% unless @profile.send("#{name}_unknown?") %>
            <tr class="text-lg">
              <td class="font-accent font-light">
                <%= Profile.human_attribute_name(name) %>
              </td>
              <td>
                <%= send "format_attr_#{name}", @profile.send(name) %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>


</div>